package com.jddev.simpletouch.ui.theme.ios

import androidx.compose.ui.graphics.Color

data class CupertinoColorScheme(
    val blue: Color,
    val brown: Color,
    val cyan: Color,
    val green: Color,
    val indigo: Color,
    val mint: Color,
    val orange: Color,
    val pink: Color,
    val purple: Color,
    val red: Color,
    val teal: Color,
    val yellow: Color,
    val gray: Color,
    val gray2: Color,
    val gray3: Color,
    val gray4: Color,
    val gray5: Color,
    val gray6: Color,
    val primaryLabel: Color,
    val secondaryLabel: Color,
    val tertiaryLabel: Color,
    val quaternaryLabel: Color,
    val placeholderText: Color,
    val link: Color,
    val primaryBackground: Color,
    val secondaryBackground: Color,
    val tertiaryBackground: Color,
    val groupedBackground: Color,
    val secondaryGroupedBackground: Color,
    val tertiaryGroupedBackground: Color,
    val fill: Color,
    val secondaryFill: Color,
    val tertiaryFill: Color,
    val quaternaryFill: Color,
    val separator: Color,
    val opaqueSeparator: Color,
    val nonadaptable: Color,
)
